name: Deployment Blue/Green

on:
  workflow_dispatch:
    inputs:
      enableBlue:
        description: 'Enables blue deployment'
        required: true
        type: choice
        options:
          - true
          - false
      enableGreen:
        description: 'Enables green deployment'
        required: true
        type: choice
        options:
          - true
          - false
      trafficDistribution:
        description: 'Traffic distribution of blue/green deployment'
        required: true
        type: choice
        options:
          - blue
          - blue-90
          - split
          - green-90
          - green

env:            
  AWS_REGION: ap-southeast-1  

jobs:
  CD:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply
      run: terraform apply -no-color -auto-approve -var 'traffic_distribution=${{ inputs.trafficDistribution }}' -var 'enable_blue_env=${{ inputs.enableBlue }}' -var 'enable_green_env=${{ inputs.enableGreen }}'

    - name: Export terraform outputs
      id: tfout
      run: |
        terraform output
